---
 - name: Add user and group permissions to sudoers
   lineinfile:
     dest=/etc/sudoers
     state=present
     regexp={{ item.regex }}
     line={{ item.line }}
     validate='visudo -cf %s'
   with_items:
    - { regex: '^%wheel', line: '%wheel ALL=(ALL) NOPASSWD: ALL' }
    - { regex: '^ansible', line: 'ansible ALL=(ALL) NOPASSWD: ALL' }
    - { regex: '^Defaults:jenkins', line: 'Defaults:jenkins !requiretty' }
    - { regex: '^jenkins', line: 'jenkins ALL=(ALL) NOPASSWD: ALL' }
    - { regex: '^Cmnd_Alias', line: 'Cmnd_Alias BUILDADMIN = /releases/.buildAdmin/*, /releases/.devBuildAdmin/*, /tmp/pkgTmpDir.*/pkgSign' }
    - { regex: '^Defaults:cvssvr', line: 'Defaults:cvssvr !requiretty' }
    - { regex: '^cvssvr', line: 'cvssvr ALL= NOPASSWD: BUILDADMIN' }
