---
######################################################
############Steps to run the playbook###################
###
###Step 1: Get into the root of the system to enable permission to configure the ssh
###Command :- Change PermitRootLogin in /etc/ssh/sshd_config to yes
###
###Step 2: Configure the repository to point to the target machine 
###Commands:- git clone repository name
###           git checkout feature/branch
###           vi inventory/stg/hosts
###           Change the IP Address to the Target IP with the label created in the hosts file
###
###Step 3: Running the playbook:- Run this playbook with root user only so that all the yum packages and pip packages get installed
###                               Prompt for the SSH Password:- When the SSH password pops up, give in the root password for that
###                               Prompt for the Vault Password:- When the vault password pops up, give in the vault password locally created (Please refer to the README.md to create a local vault)
###Commands:- Running the playbook.
###           ansible-playbook -i inventory/stg -u root --ask-pass playbook name   --ask-vault-pass  -vvvv

- hosts: host_slave_node
  become: yes
  remote_user: root 
  become_method: sudo
  pre_tasks:
   - name: Creating Jenkins group
     group: name="jenkins" gid=500

  roles:
    - server-configure-jenkins-user
    - server-configure-sudoers
    - server-deploy-jenkins-controller_slave
  vars:
   vault_key_encrypted: 'vaultvars.yml'
        
