- name: Copy mrepo Configuration
  copy: >
    src={{ item.src }}
    dest={{ item.dest }}
    owner=root
    group=root
    mode={{ item.mode }}
  with_items:
    - { src: "files/mrepo_configs/mrepo.conf", dest: "/etc/mrepo.conf", mode: '0644' }
    - { src: "files/mrepo_configs/mrepo.conf.d/", dest: "/etc/mrepo.conf.d/", mode: '0644' }
    - { src: "files/mrepo_configs/certs/redhat-uep.pem", dest: "/etc/pki/CA/certs/", mode: '0644' }
    - { src: "files/mrepo_configs/certs/rhel7-x86_64-403d9f32-c502-4a1f-8cdb-44f541fe2808.pem", dest: "/etc/pki/entitlement/", mode: '0600' }
    - { src: "files/mrepo_configs/certs/rhel7-x86_64-8a85f9815bfd5f79015bfd94494d3a64.pem", dest: "/etc/pki/entitlement/", mode: '0644' }
    - { src: "files/mrepo_configs/certs/rhel6-i386-662924f0-e17b-4257-8ecf-6bdb76805931.pem", dest: "/etc/pki/entitlement/", mode: '0600' }
    - { src: "files/mrepo_configs/certs/rhel6-i386-8a85f9815bfd5f79015bfd94494d3a64.pem", dest: "/etc/pki/entitlement/", mode: '0644' }
    - { src: "files/mrepo_configs/certs/rhel5-i386-38edf661-f9a3-4ca5-9ec6-a1d60f43730e.pem", dest: "/etc/pki/entitlement/", mode: '0600' }
    - { src: "files/mrepo_configs/certs/rhel5-i386-8a85f9815bfd5f79015bfd94494d3a64.pem", dest: "/etc/pki/entitlement/", mode: '0644' }
    - { src: "files/mrepo_configs/certs/rhel5-x86_64-91ff43b3-ef9b-47ad-952a-774484d4ab32.pem", dest: "/etc/pki/entitlement/", mode: '0600' }
    - { src: "files/mrepo_configs/certs/rhel5-x86_64-8a85f9815bfd5f79015bfd94494d3a64.pem", dest: "/etc/pki/entitlement/", mode: '0600' }
    - { src: "files/mrepo_configs/certs/rhel6-x86_64-5e9b1ea1-76e8-4dc2-b7d9-e3c1cffcadf6.pem", dest: "/etc/pki/entitlement/", mode: '0644' }
    - { src: "files/mrepo_configs/certs/rhel6-x86_64-8a85f9815bfd5f79015bfd94494d3a64.pem", dest: "/etc/pki/entitlement/", mode: '0644' }
  tags:
    - config_files

- name: "mrepo Nightly Updates"
  cron:
    minute={{ item.minute }}
    hour={{ item.hour }}
    job={{ item.command }}
    name={{ item.name }}
  with_items:
   - { minute: '0',  hour: '1', command: '/usr/bin/mrepo -q -ug rhel-5Server-i386', name: 'RHEL 5 i386' }
   - { minute: '30', hour: '1', command: '/usr/bin/mrepo -q -ug rhel-5Server-x86_64', name: 'RHEL 5 x85_64' }
   - { minute: '0',  hour: '2', command: '/usr/bin/mrepo -q -ug rhel-6Server-i386', name: 'RHEL 6 i386' }
   - { minute: '30', hour: '2', command: '/usr/bin/mrepo -q -ug rhel-6Server-x86_64', name: 'RHEL 6 x86_64' }
   - { minute: '0',  hour: '3', command: '/usr/bin/mrepo -q -ug centos6-i386', name: 'CentOS 6 i386' }
   - { minute: '30', hour: '3', command: '/usr/bin/mrepo -q -ug centos6-x86_64', name: 'CentOS 6 x86_64' }
   - { minute: '0',  hour: '4', command: '/usr/bin/mrepo -q -ug rhel-7Server-x86_64', name: 'RHEL 7 x86_64' }
   - { minute: '30', hour: '4', command: '/usr/bin/mrepo -q -ug centos7-x86_64', name: 'CentOS 7 x86_64' }
  tags:
    - config_files

- name: Create 64 Loop Devices
  lineinfile:
    dest: /etc/rc.local
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^/sbin/MAKEDEV', line: '/sbin/MAKEDEV -m 64 /dev/loop' }
  tags:
    - config_files
