- name: Create Coverity and Jenkins Groups
  group: >
    gid={{ item.gid }}
    name={{ item.name }}
  with_items:
    - { gid: '503', name: 'coverity' }
    - { gid: '500', name: 'jenkins' }
    - { gid: '48', name: 'apache' }

- name: Create Coverity User
  user: >
    uid={{ item. uid }}
    group={{ item.group }}
    name={{ item.name }}
    home={{ item.home }}
    shell={{ item.shell }}
    comment={{ item.comment }}
  with_items:
    - { uid: '503', name: 'coverity', group: 'coverity', comment: 'Coverity', home: '/var/www/coverity', shell: '/bin/bash' }
    - { uid: '500', name: 'jenkins', group: 'jenkins', comment: 'Jenkins', home: '/home/jenkins', shell: '/bin/bash' }
    - { uid: '48', name: 'apache', group: 'apache', comment: 'Apache', home: '/var/www', shell: '/bin/bash' }

- name: Create components Link
  file:
    src=/srv/components
    dest=/components
    state=link

- name: Create Mrepo Directories
  file: path="{{ item[0] }}{{ item[1] }}" state=directory
  with_nested:
    - [ '/var/mrepo/', '/var/www/mrepo/' ]
    - [ 'centos6-i386', 'centos6-x86_64', 'centos7-x86_64', 'rhel-5Server-i386', 'rhel-5Server-x86_64', 'rhel-6Server-i386', 'rhel-6Server-x86_64', 'rhel-7Server-x86_64', 'jpackage-generic-1.7-noarch', 'jpackage-generic-5.0-noarch' ]
  tags:
    - config_files
