---
- name: install setuptools for easy_install
  yum:
   name: python-setuptools.noarch
   state: latest

- name: installing pip via command line. The module doesnt work because its stupid.
  command: easy_install pip

- name: installing openpyxl via pip
  pip:
    name: docker-py
    state: latest

- name: Build pulse image
  docker_image:
     path: /var/lib/jenkins/idocker/rhel68-Pulse-Base_Config
     name: pulse1.0
