---
- name: Check out idocker from git
  git:
    repo: "{{ jenkins_jobs_git_url }}"
    version: "{{ jenkins_jobs_git_ref }}"
    dest: /var/lib/jenkins/idocker
    accept_hostkey: yes
    force: no
    update: yes
    key_file: /var/lib/jenkins/.ssh/id_rsa
  become: yes
  become_user: jenkins
