---

- name: Install nfs-utils
  package:
    name: nfs-utils
    state: present

- name: Ensure NFS required services are running
  service:
    name: rpcbind
    enabled: yes
    state: started

- name: Create mount points to get a read-only mount of artifacts on /components
  file:
    path: /artifacts/ro/components
    state: directory
    owner: jenkins
    group: jenkins

    # Note: IT has to poke hole in firewall for these to be truly "rw"
- name: Mount read-only components NFS share.
  mount:
    name: /artifacts/ro/components
    src: '10.250.251.50:/ENG_Releases'
    fstype: nfs
    opts: ro,auto,vers=3,noatime,soft,intr
    state: mounted
