---

#- name: Create Logical Volume lv_var_components in volume group vg_primary
#  lvol:
#   vg: vg_primary
#   lv: lv_var_components
#   size: 100g
#  when: is_prod_check == "no"

#- filesystem:
#    fstype: xfs
#    dev: /dev/vg_primary/lv_var_components
#  when: is_prod_check == "no"
#
#- name: create components directory
#  file:
#    path: /components
#    state: directory
#    mode: 0755
#    owner: jenkins
#    group: jenkins
#
#- name: Mount /components with logical volume lv_var_atlassian
#  mount:
#    name: /components
#    src: /dev/vg_primary/lv_var_components
#    fstype: xfs
#    opts: rw
#    state: mounted
#  when: is_prod_check == "no"
#
  # Note: IT has to poke hole in firewall for these to be truly "rw"
- name: Mount components NFS share. For Production builds only.
  mount:
    name: /components
    src: '10.250.251.50:/ENG_Releases'
    fstype: nfs
    opts: rw,auto,vers=3,noatime,soft,intr
    state: mounted
  when: is_prod_check == "yes"

- name: after mount make components owned by jenkins
  file:
    path: /components
    owner: jenkins
    group: jenkins
    mode: 0755
