---
 - name: Add Jenkins user
   group:
     name: jenkins
     gid: 500

 - name: Add Jenkins user
   user:
     name: jenkins
     group: jenkins
     uid: 500
     createhome: yes

# An apparent ansible bug results in /home/jenkins being owned by root. This is a workaround for that bug.
 - name: Make sure jenkins owns it's own home directory.
   file:
     path: /home/jenkins
     owner: jenkins
     group: jenkins
     state: directory

 - name: Install ssh keys
   copy:
     content: "{{ jenkins_key }}"
     dest: /home/jenkins/.ssh/id_rsa
     mode: 0400
     owner: jenkins
   when: jenkins_key is defined

 - name: Setup up Jenkins /builds folder
   file:
     path: /builds
     owner: jenkins
     group: jenkins
     state: directory

 - name: Setup authorized keys
   authorized_key:
     key: "{{ jenkins_public_key }}"
     user: jenkins
   when: jenkins_public_key is defined
