---
  - name: Install Packages (Debian)
    apt:
      name: "{{ item }}"
      state: latest
      force: yes
      update_cache: yes
    with_items: "{{ apt_packages }}"
    when: ansible_os_family == 'Debian'

  - name: Install Packages (RedHat)
    yum:
      name: "{{ item }}"
      state: latest
    with_items: "{{ yum_packages }}"
    when: ansible_os_family == 'RedHat'

  - name: Install NPM packages
    npm:
      name: "{{ item }}"
      global: yes
      registry: "{{ npm_registry }}"
    with_items: "{{ npm_packages }}"
    when: npm_packages is defined
