---

- block:
  - lineinfile:
      dest: /etc/init.d/jenkins
      state: absent
      regexp: '^JAVA_CMD='
  - lineinfile:
      dest: /etc/init.d/jenkins
      state: present
      line: 'JAVA_CMD="$JENKINS_JAVA_CMD $JENKINS_JAVA_OPTIONS -Dhudson.plugins.active_directory.ActiveDirectorySecurityRealm.forceLdaps=true -DJENKINS_HOME=$JENKINS_HOME -jar $JENKINS_WAR"'
      insertbefore: '^PARAMS='
  - file:
      path: /etc/pki/java/cacerts
      state: absent
  - copy:
      src: files/cacerts
      dest: /etc/pki/java/cacerts
      owner: root
      group: root
      mode: 0644
