---
- include: upgrade-jenkins.yml
  when: jenkins_upgrade_var is defined

- include: ssh-and-config.yml

- name: Installing required yum packages
  yum: name={{item}} state=latest
  with_items:
    - git
    - ansible
    - graphviz-gd

- include: port-forward.yml
  when:
   - ansible_distribution == "RedHat"
   - ansible_distribution_major_version >= "7"

- name: Check if jenkins installed or clean install requested
  stat: path=/var/lib/jenkins/.ansible-run-check
  register: ansible_run_check

- block:
  - name: Clone Jenkins Backup
    git:
     repo: ssh://git@vault.idirect.net/devops/jenkins-backup.git
     dest: /tmp/jenkins-backup-archive

  - name: Remove .git file
    file: path=/var/lib/jenkins/.git state=absent

  - name: Copy Jenkins archive to jenkins home folder
    shell: "cp -R /tmp/jenkins-backup-archive/* /var/lib/jenkins/"

  - name: Create stat file to register ansible run
    file: path=/var/lib/jenkins/.ansible-run-check owner=jenkins group=jenkins mode=0644 state=touch

  - name: Remove jenkins archive file
    file: path=/tmp/jenkins-backup-archive state=absent

  - name: Update direcotory permission and restart jenkins
    file:
     path: /var/lib/jenkins
     owner: jenkins
     group: jenkins
     recurse: yes
    notify: restart jenkins
  when:
    - ansible_run_check.stat.exists == False
    - clean_install is not defined
  become_user: jenkins
  become_method: sudo



# - name: Get jenkins archive from Bitbucket
#   become_method: sudo
#   become_user: jenkins
#   shell: "git archive --remote=ssh://git@vault.idirect.net/devops/jenkins-backup.git master | tar -x -C '/var/lib/jenkins/'"
#   notify: restart jenkins
