---
- name: Testing the VG has 10G free
  shell: vgdisplay | grep "VG Name" | cut -d " " -f 19
  register: vgnamevar

- debug: var=vgnamevar.stdout


- name: Changing name to vg00 if not set
  shell: /usr/sbin/vgrename vg_primary vg00
  when: vgnamevar.stdout != "vg00" 

- name: Create Logical Volume lv_var_atlassian in volume group vg00
  lvol:
   vg: vg00
   lv: lv_var_atlassian
   size: 89g

- filesystem:
    fstype: xfs
    dev: /dev/vg00/lv_var_atlassian

- file:
    path: /var/atlassian/
    state: directory
    mode: 0755

- name: Mount /var/atlassion with logical volume lv_var_atlassian
  mount:
    name: /var/atlassian
    src: /dev/vg00/lv_var_atlassian
    fstype: xfs
    opts: rw
    state: mounted

- file:
    path: "{{ bitbucket_home }}"
    state: directory
    mode: 0755

