---


- name: Add idirect rhel extra repo
  yum_repository:
    name: idirect-rhel-extras
    description: Red Hat Enterprise Extra Linux repository
    baseurl: http://repos.eng.idirect.net/mrepo/rhel-{{ ansible_distribution_major_version }}Server-$basearch/RPMS.extras/
    metadata_expire: 1
    cost: 1
    enabled: yes
    gpgcheck: yes
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release


- name: install docker
  yum:
   name: "{{ item }}" 
   enablerepo: idirect-rhel-extras
   state: latest
  with_items:
  - docker 
  - device-mapper-libs
  - device-mapper-event-libs

- name: Make sure docker service is running
  systemd: 
    state: started 
    name: docker.service

- name: enable service docker and ensure it is not masked
  systemd:
    name: docker.service
    enabled: yes
    masked: no
