---
- name: Install Java OPenJDK
  yum:
    name: java-1.8.0-openjdk.x86_64 
    state: present
        
- name: Insatll Git
  yum:
    name: git
    state: latest

- name: Remove JDK7 archive
  file: path=${jvm_folder}/$jdk_archive state=absent
  
 
- pause:
    seconds: 40
- name: Create .ssh folder
  file: 
    path: /home/jenkins/.ssh 
    state: directory 
    mode: 0700 
    owner: jenkins
- pause:
    seconds: 6 
 

##The Instllation of GIT on the controller
- name: Clone BitBucket Repo
  git:
    repo: <Repository Name> 
    dest: /home/jenkins/Temporary_directory_created
    accept_hostkey: yes
    force: yes
    update: yes
    key_file: /home/jenkins/.ssh/id_rsa
  become_user: jenkins

###These packages are installed for the Jenkins jobs setup for the traffic generation
- name: Install Python-setuptools
  yum:
    name: python-setuptools
    state: latest

- include: yum_packages.yml

- easy_install:
    name: pip
    state: latest

- include: pip_packages.yml 

- name: Install the Robot Framework
  pip:
    name: /home/jenkins/Temporary_directory_created/Robot/


- debug:
    msg: "You have reached to the end of the playbook...!!!!You can login to your runner and continue with your tasks on it...!!!"
